### ISSUE TITLE
AudioSource crash

### ISSUE THREAD

**Issue by innerviewer** [Monika0000/SREngine#19]
**Describe the bug**
Application crash (assertion) on scene launch.

**To Reproduce**
1. Run the application in debug mode.
2. Add a new game object with AudioSource component attached to it.
3. Do not add a path, but you may try to change volume.
4. Run the scene, get application crashed.

**Comment by CaptainSlider** [comment]
сбой был из-за того что в функции SoundManager Play не было проверки на наличие пути
